-   id: run-python
    name: Run python
    description: Run any python command, use additional_dependencies to add necessary packages.
    entry: run-python
    language: python
-   id: run-node
    name: Run node
    description: Run any node command, use additional_dependencies to add necessary packages.
    entry: run-node
    language: node
